version: '3'
services:
  mysql:
    build:
      context: ./mysql/
      args:
        baseImageVersion: 0.14.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - USE_DB_ID=true
